name: Session proposal
description: Propose to chair a breakout session at TPAC
labels: ["session"]
body:
# This repo includes code that validates instances of the data below. 
# The validation code parses this file and uses "id" for some aspects of validation. 
# One implication is that labels below can be changed without disrupting some of the validation code.
# However, the validation code in some cases also matches on values of "options" below, so if those change,
# you will need to change the validation code as well.

  - type: markdown
    attributes:
      value: |
        Thank you for proposing to chair a TPAC breakout session. Please ensure that the session is [in scope for a TPAC breakout](https://github.com/w3c/tpac-breakouts/wiki/Policies#session-scope) and review the [good practices for session chairs](https://github.com/w3c/tpac-breakouts/wiki/Good-Practices-for-Session-Chairs), which includes information about [how you can later update your session](https://github.com/w3c/tpac-breakouts/wiki/Good-Practices-for-Session-Chairs#how-to-update-a-session).

  - type: textarea
    id: description
    attributes:
      label: Session description
      description: |
        Simple markdown only please (inline formatting, links, lists).
    validations:
      required: true

  - type: input
    id: goal
    attributes:
      label: Session goal
    validations:
      required: true

  - type: textarea
    id: chairs
    attributes:
      label: Additional session chairs (Optional)
      description: |
        GitHub identities of additional session chairs other than you (e.g., `@tidoust, @ianbjacobs`). Space- or comma-separated list.
    validations:
      required: false

  - type: input
    id: shortname
    attributes:
      label: IRC channel (Optional)
      description: |
        Shortname for the irc.w3.org channel (e.g., `my-fav-session`). If not provided, shortname will be generated from title.
    validations:
      required: false

  - type: dropdown
    id: attendance
    attributes:
      label: Who can attend
      description: |
        TPAC breakouts sessions are usually open to the public (including remote attendees). Please only select “Restricted” if there is a compelling reason why the session should only be open to TPAC registrants.
      options:
        - Anyone may attend (Default)
        - Restricted to TPAC registrants
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Preferences

  - type: dropdown
    id: duration
    attributes:
      label: Session duration
      options:
        - 60 minutes (Default)
        - 30 minutes
    validations:
      required: true

  - type: textarea
    id: conflicts
    attributes:
      label: Other sessions where we should avoid scheduling conflicts (Optional)
      description: |
        Identify sessions by their issue number in this GitHub repo (e.g., `#32, #18`). Space- or comma-separated list.
    validations:
      required: false

  - type: dropdown
    id: capacity
    attributes:
      label: Estimated number of in-person attendees
      options:
        - Don't know (Default)
        - Fewer than 20 people
        - 20-45 people
        - More than 45 people
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
      label: Comments (Optional)
      description: |
        Any additional input, including timing constraints, that we should be aware of.
    validations:
      required: false

  - type: textarea
    id: materials
    attributes:
      label: Meeting materials
      description: |
        As the agenda and meeting materials become available, you will be able to update your session description in markdown to add links. Similarly, after the meeting, you can link to minutes.

        **PLEASE ONLY EDIT BY REPLACING @@ with URLs!**
      value: |
        - Agenda: @@
        - Slides: @@
        - Minutes: @@
